version: '3.2'

services:
  db_mongo:
    image: mongo:4.2
    container_name: db_mongo
    restart: always
    ports:
     - 27017:27017
    environment:
      MONGO_INIT_DATABASE: wallet
    volumes:
      - db_mongo-volume:/var/lib/mongo/data

  node:
    container_name: node
    build: ./back-end
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db_mongo
    env_file:
      - back-end/.env
  
  react:
    container_name: react
    build: ./front-end
    volumes:
      - react-volume:/var/www/html
  
  nginx:
    container_name: nginx_app
    build: ./nginx
    restart: always
    ports:
      - 8081:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - db_mongo
      - node
      - react

volumes:
  db_mongo-volume:
  react-volume:
